#!/bin/bash

for file in $PWD/dotfiles/\.[a-zA-Z]*
do
  if [ -f $file ]; then
    ln -sFv $file $HOME/`basename ${file}`
  fi
done

ln -sFv $PWD/oh-my-zsh/ $HOME

mkdir -p $HOME/.vim/colors
ln -sFv $PWD/resources/vim/base16-nerdnoir.vim $HOME/.vim/colors/base16-nerdnoir.vim
